import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { authAPI } from '../api/auth';
import './TwoFactorModal.css';

interface TwoFactorModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
  action: 'enable' | 'disable';
}

export default function TwoFactorModal({ isOpen, onClose, onSuccess, action }: TwoFactorModalProps) {
  const { t } = useTranslation();
  const [step, setStep] = useState<'setup' | 'verify'>('verify');
  const [secret, setSecret] = useState('');
  const [qrCodeUrl, setQrCodeUrl] = useState('');
  const [code, setCode] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    if (isOpen) {
      setCode('');
      setError('');
      if (action === 'enable') {
        setStep('setup');
        loadSetupData();
      } else {
        setStep('verify');
      }
    }
  }, [isOpen, action]);

  const loadSetupData = async () => {
    setIsLoading(true);
    setError('');
    try {
      const { data } = await authAPI.setup2FA();
      setSecret(data.secret);
      setQrCodeUrl(data.qr_code_url);
    } catch (err: any) {
      setError(err.response?.data?.error || t('auth.setup_2fa_error', 'Failed to initialize 2FA setup.'));
    } finally {
      setIsLoading(false);
    }
  };

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
      if (action === 'enable') {
        await authAPI.enable2FA(code);
      } else {
        await authAPI.disable2FA(code);
      }
      onSuccess();
      onClose();
    } catch (err: any) {
      setError(err.response?.data?.error || t('auth.verify_2fa_error', 'Invalid code. Please try again.'));
    } finally {
      setIsLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content animate-slide-up" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h2>
            {action === 'enable'
              ? t('auth.enable_2fa_title', 'Enable Two-Factor Authentication')
              : t('auth.disable_2fa_title', 'Disable Two-Factor Authentication')}
          </h2>
          <button className="modal-close-btn" onClick={onClose}>&times;</button>
        </div>

        <div className="modal-body">
          {error && <div className="modal-error-banner">{error}</div>}

          {isLoading && !qrCodeUrl && (
            <div className="modal-loading-spinner">{t('common.loading', 'Loading...')}</div>
          )}

          {action === 'enable' && step === 'setup' && qrCodeUrl && (
            <div className="setup-container">
              <p className="setup-instructions">
                {t(
                  'auth.scan_qr_desc',
                  'Scan the QR code below using your Google Authenticator, Authy, or Microsoft Authenticator app.'
                )}
              </p>
              
              <div className="qr-code-wrapper">
                <img
                  src={`https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(
                    qrCodeUrl
                  )}`}
                  alt="2FA QR Code"
                  className="qr-code-image"
                />
              </div>

              <div className="secret-key-display">
                <span className="secret-label">{t('auth.secret_key', 'Secret Key')}:</span>
                <code className="secret-code">{secret}</code>
              </div>

              <button
                type="button"
                className="btn btn-primary btn-md next-btn"
                onClick={() => setStep('verify')}
              >
                {t('common.next', 'Next')}
              </button>
            </div>
          )}

          {(action === 'disable' || step === 'verify') && (
            <form onSubmit={handleVerify} className="verify-container">
              <p className="verify-instructions">
                {action === 'enable'
                  ? t('auth.verify_instructions_enable', 'Enter the 6-digit code generated by your authenticator app to complete the setup.')
                  : t('auth.verify_instructions_disable', 'Enter the 6-digit code from your authenticator app to confirm disabling two-factor authentication.')}
              </p>

              <div className="form-group otp-group">
                <input
                  type="text"
                  maxLength={6}
                  pattern="\d{6}"
                  inputMode="numeric"
                  placeholder="000000"
                  className="otp-input-field"
                  value={code}
                  onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))}
                  required
                  autoFocus
                  disabled={isLoading}
                />
              </div>

              <div className="modal-footer-actions">
                <button
                  type="button"
                  className="btn btn-secondary"
                  onClick={action === 'enable' ? () => setStep('setup') : onClose}
                  disabled={isLoading}
                >
                  {action === 'enable' ? t('common.back', 'Back') : t('common.cancel', 'Cancel')}
                </button>
                <button
                  type="submit"
                  className="btn btn-primary"
                  disabled={isLoading || code.length !== 6}
                >
                  {isLoading ? t('common.loading', 'Loading...') : t('common.verify', 'Verify')}
                </button>
              </div>
            </form>
          )}
        </div>
      </div>
    </div>
  );
}
